
DROP TABLE IF EXISTS "words";
CREATE TABLE IF NOT EXISTS "words" (
	"id"	INTEGER UNIQUE,
	"word"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "clues";
CREATE TABLE IF NOT EXISTS "clues" (
	"id"	INTEGER UNIQUE,
	"clue"	TEXT NOT NULL,
	"wordId"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	CONSTRAINT "Clue to Word FK" FOREIGN KEY("wordId") REFERENCES "words"("id") ON DELETE CASCADE
);